### ISSUE TITLE
Feature request: `Version` filter for `Last Updated` sort

### ISSUE THREAD

**Issue by Krutoy242** [SuperStormer/cf-search#1]
Im making 1.12 modpack. Sometimes i need to search for new or maintained mods.
Sorted by update date, and it show me 1.19 version updates.

![image](https://user-images.githubusercontent.com/936618/189543856-26e301ad-4741-4c47-a807-ea4e0bae161f.png)

Please add feature: if i search for 1.12, `Last Updated` sort only on actually 1.12 version updates, not any version.

In example above, Ore Excavation was updated for only 1.12 several years ago.

**Comment by SuperStormer** [comment]
Unfortunately, I don't think this is feasible as the curseforge API provides no way to sort by last updated by MC version, and sorting manually would require fetching the entire 1.12 mod list.
