### ISSUE TITLE
some mods dont show

### ISSUE THREAD

**Issue by Dan4oby** [SuperStormer/cf-search#10]
for example without version "Minecraft 1.12" filter i can find mod named Dead Cells 
https://legacy.curseforge.com/minecraft/mc-mods/dead-cells
using this filter I can't find it, but this mod is for 1.12.2

Also, there is one problem - I can't get past page 400(page size is 25). It just appears an endless "loading..." and nothing happens

**Comment by SuperStormer** [comment]
For the first issue: it shows up at the bottom of the first page for me with [default filters](https://superstormer.github.io/cf-search/?classId=6&categoryId=&gameVersionTypeId=&gameVersion=&sortField=6&sortOrder=desc&pageSize=50&searchFilter=dead+cells&filtersInclude=&filtersExclude=&maxVer=&minVer=). 

For the second issue: This appears to be a limitiation of the Curseforge API, but I will add some proper error handling for this case.
![image](https://github.com/SuperStormer/cf-search/assets/41648788/ec896e5f-f2bc-4e95-b29d-48bcb1c4a452)

**Comment by Dan4oby** [comment]
> For the first issue: it shows up at the bottom of the first page for me

You didnt understand me right. With default filters - yes, you can find it, but if you set version filter to "Minecraft 1.12" (which is main version of this mod) you cant find it

**Comment by SuperStormer** [comment]
![image](https://github.com/SuperStormer/cf-search/assets/41648788/23486924-474f-48ee-b3fd-75cb47be5e91)
Interesting, the `gameVersionTypeId` is usually supposed to be a `628` for "Minecraft 1.12", but for some reason it's null here.

**Comment by SuperStormer** [comment]
So the good news is that this is probably fixable for cases where both version and sub-version are selected. Unfortunately, I'm not sure if it's possible to fix searches where *only* the version is selected. Why is the Curseforge API so bad...

**Comment by Dan4oby** [comment]
> So the good news is that this is probably fixable for cases where both version and sub-version are selected. Unfortunately, I'm not sure if it's possible to fix searches where _only_ the version is selected. Why is the Curseforge API so bad...

ok, this would help a lot, because I looked twice through all the mods for 1.12.2 on your site, and only realized towards the end that your search lost 55-60 pages of mods

**Comment by Dan4oby** [comment]
i also have one feature suggestion. 
Can you add license filter in resourcepacks? It would be very very useful to find open source resourcepacks

**Comment by SuperStormer** [comment]
Not exposed by the API, sorry.

**Comment by SuperStormer** [comment]
The first issue should also be fixed now.
