### ISSUE TITLE
Feature Request - filter modpacks by mod dependancies. 

### ISSUE THREAD

**Issue by dvance12** [SuperStormer/cf-search#13]
On Curse's website you can find a mod you are interested in and then look at what modpacks include it, but then you are left searching through a ton of modpacks with no way to filter versions or other mods you maybe interested in. 

An example would be if I was looking for modpacks that included refined storage and project expansion and were Minecraft version 1.18 or newer, there is currently no way to do this. I would be stuck with picking one of those mods and then searching through 30+ pages of modpacks that have that mod as a dependency just to click on one and see that it is running Minecraft 1.12 or doesn't have refined storage.

**Comment by SuperStormer** [comment]
Someone's already made a site for this: https://www.modpackindex.com/modpack/finder
