### ISSUE TITLE
[Request] Ability to filter out MCreator mods

### ISSUE THREAD

**Issue by katubug** [SuperStormer/cf-search#15]
Hi! I love your tool, I use it all the time and recommend it to people constantly. So firstly, thank you VERY much for making it!

Secondly, I would love if there was a feature to exclude mods with the MCreator category.

I've tried sorting it by adding every category EXCEPT MCreator, but then it doesn't show any mods, even with max page size: https://i.imgur.com/deYc3jl.png

I know this won't filter out mods which don't add that category, but it would at least make things a little easier for me. Thank you!

**Comment by SuperStormer** [comment]
Click twice on any checkbox to exclude it.
For example: 
https://superstormer.github.io/cf-search/?categoryId=6484&sortField=2 (default)
https://superstormer.github.io/cf-search/?categoryId=6484&sortField=2&filtersExclude=4906 (excluding MCreator)

On Chrome, this displays as
![image](https://github.com/SuperStormer/cf-search/assets/41648788/8cbeb9bd-9a4c-4ed8-b82c-c2984d45e1a4)
and Firefox has something similar.

**Comment by SuperStormer** [comment]
Additionally, selecting two visual filters means `filter1 AND filter2`, **not** `filter1 OR filter2` (FWIW, this is also how both new Curseforge and Modrinth handle filters).
