### ISSUE TITLE
[Feature request] Displaying mod author and filtering by author.

### ISSUE THREAD

**Issue by mortuusars** [SuperStormer/cf-search#5]
An option to show mod author alongside mod name would be nice.
Also filtering out specific mod authors would be useful sometimes. (Yes, the one author whose name starts with 'S')

**Comment by SuperStormer** [comment]
The first part is done (though I still need to fix the CSS for mobile screens).

**Comment by Primitive-Human** [comment]
Any updates on the second part? That same author is really bloating and I never intend to use his mods anyway.
