### ISSUE TITLE
Some mods links go to incorrect URL

### ISSUE THREAD

**Issue by Vocaa** [SuperStormer/cf-search#8]
Some mod links go to an incorrect URL, ex:
"Philip's Ruins" goes to "https://7daystodie.curseforge.com/minecraft/mc-mods/ruins"
"Bedrockify" goes to "https://7daystodie.curseforge.com/minecraft/mc-mods/bedrockify"

Manually removing '7daystodie' from the start produces a working URL

If searched for on the official curseforge site, the URLs are correct

**Comment by SuperStormer** [comment]
curseforge api being bad as usual, fixed.
